language: android
jdk:      oraclejdk8
android:
  components:
    - tools
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943
    - platform-tools
    - build-tools-25.0.2
    - android-25
